[workspace]
platforms = ['linux-64', 'osx-arm64', 'osx-64', 'win-64']

name = "hansen_deforestation"
channels = [
  'https://repo.prefix.dev/ecoscope-workflows/',
  'https://repo.prefix.dev/ecoscope-workflows-custom/',
  'conda-forge',
]

[dependencies]
wt-compiler = "==0.8.1"
graphviz = "*"

[tasks.compile-hansen-deforestation]
cmd = './dev/recompile.sh --install'

[tasks.recompile-hansen-deforestation]
cmd = './dev/recompile.sh --update'
