# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


# ruff: noqa: E402

# %% [markdown]
# # Hansen Deforestation
# TODO: top level description

# %% [markdown]
# ## Imports

import os

from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.groupby import split_groups as split_groups
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.io import set_gee_connection as set_gee_connection
from ecoscope_workflows_core.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.results import (
    merge_widget_views as merge_widget_views,
)
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    load_spatial_features_group as load_spatial_features_group,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    draw_historic_timeseries as draw_historic_timeseries,
)
from ecoscope_workflows_ext_gamm_trend_analysis.tasks import (
    extract_forest_cover_trends as extract_forest_cover_trends,
)
from ecoscope_workflows_ext_gamm_trend_analysis.tasks import (
    fit_gamm_model as fit_gamm_model,
)
from ecoscope_workflows_ext_gamm_trend_analysis.tasks import (
    predict_gamm_trends as predict_gamm_trends,
)

# %% [markdown]
# ## Set Workflow Details

# %%
# parameters

workflow_details_params = dict(
    name=...,
    description=...,
    image_url=...,
)

# %%
# call the task


workflow_details = (
    set_workflow_details.set_task_instance_id("workflow_details")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**workflow_details_params)
    .call()
)


# %% [markdown]
# ## Connect to Earth Engine

# %%
# parameters

gee_project_name_params = dict(
    data_source=...,
)

# %%
# call the task


gee_project_name = (
    set_gee_connection.set_task_instance_id("gee_project_name")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**gee_project_name_params)
    .call()
)


# %% [markdown]
# ## Time Range

# %%
# parameters

time_range_params = dict()

# %%
# call the task


time_range = (
    set_time_range.set_task_instance_id("time_range")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        time_format="%d %b %Y %H:%M:%S %Z",
        timezone={
            "label": "UTC",
            "tzCode": "UTC",
            "name": "Universal Coordinated Time",
            "utc": "+00:00",
        },
        since="2000-01-01T00:00:00.000Z",
        until="2023-12-31T23:59:59.000Z",
        **time_range_params,
    )
    .call()
)


# %% [markdown]
# ## Set Groupers

# %%
# parameters

groupers_params = dict(
    groupers=...,
)

# %%
# call the task


groupers = (
    set_groupers.set_task_instance_id("groupers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**groupers_params)
    .call()
)


# %% [markdown]
# ## Load Region of Interest

# %%
# parameters

roi_params = dict(
    config=...,
)

# %%
# call the task


roi = (
    load_spatial_features_group.set_task_instance_id("roi")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**roi_params)
    .call()
)


# %% [markdown]
# ## Split ROIs by Group

# %%
# parameters

split_roi_groups_params = dict()

# %%
# call the task


split_roi_groups = (
    split_groups.set_task_instance_id("split_roi_groups")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(df=roi, groupers=groupers, **split_roi_groups_params)
    .call()
)


# %% [markdown]
# ## Extract Forest Cover Trends

# %%
# parameters

forest_cover_trends_params = dict(
    tree_cover_threshold=...,
    scale=...,
    max_pixels=...,
)

# %%
# call the task


forest_cover_trends = (
    extract_forest_cover_trends.set_task_instance_id("forest_cover_trends")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(client=gee_project_name, **forest_cover_trends_params)
    .mapvalues(argnames=["aoi"], argvalues=split_roi_groups)
)


# %% [markdown]
# ## Fit GAMM Model

# %%
# parameters

gamm_model_params = dict(
    metric=...,
    degree_of_freedom=...,
    degree=...,
    family=...,
)

# %%
# call the task


gamm_model = (
    fit_gamm_model.set_task_instance_id("gamm_model")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        time_column="year",
        value_column="survival_area",
        alpha=None,
        lower_bound=None,
        upper_bound=None,
        optimize_alpha=True,
        **gamm_model_params,
    )
    .mapvalues(argnames=["dataframe"], argvalues=forest_cover_trends)
)


# %% [markdown]
# ## Generate Trend Predictions

# %%
# parameters

trend_predictions_params = dict()

# %%
# call the task


trend_predictions = (
    predict_gamm_trends.set_task_instance_id("trend_predictions")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(time_values=None, include_ci=True, **trend_predictions_params)
    .mapvalues(argnames=["model_params"], argvalues=gamm_model)
)


# %% [markdown]
# ## Create Forest Cover Trend Chart

# %%
# parameters

forest_cover_chart_params = dict(
    widget_id=...,
)

# %%
# call the task


forest_cover_chart = (
    draw_historic_timeseries.set_task_instance_id("forest_cover_chart")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        dataframe=trend_predictions,
        current_value_column="y",
        time_column="time",
        current_value_title="Observed Survival Area",
        historic_min_column="ci_lower",
        historic_max_column="ci_upper",
        historic_mean_column="predicted",
        historic_mean_title="GAM Mean",
        historic_band_title="GAM 95% CI",
        layout_style={
            "title": "Forest survival area trend (GAM)",
            "xaxis": {"title": "Year"},
            "yaxis": {"title": "Survival Area (acres)"},
        },
        upper_lower_band_style={"mode": "lines", "line": {"color": "green"}},
        historic_mean_style=None,
        current_value_style=None,
        **forest_cover_chart_params,
    )
    .mapvalues(argnames=["dataframe"], argvalues=trend_predictions)
)


# %% [markdown]
# ## Persist Forest Cover Trend Chart as Text

# %%
# parameters

persist_forest_cover_params = dict(
    filename=...,
    filename_suffix=...,
)

# %%
# call the task


persist_forest_cover = (
    persist_text.set_task_instance_id("persist_forest_cover")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        text=forest_cover_chart,
        **persist_forest_cover_params,
    )
    .mapvalues(argnames=["text"], argvalues=forest_cover_chart)
)


# %% [markdown]
# ## Create Forest Cover Trend Chart Widget

# %%
# parameters

forest_cover_widget_params = dict()

# %%
# call the task


forest_cover_widget = (
    create_plot_widget_single_view.set_task_instance_id("forest_cover_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(title="Forest Cover Trend Chart", **forest_cover_widget_params)
    .map(argnames=["view", "data"], argvalues=persist_forest_cover)
)


# %% [markdown]
# ## Merge Forest Cover Widget Views

# %%
# parameters

grouped_forest_cover_params = dict()

# %%
# call the task


grouped_forest_cover = (
    merge_widget_views.set_task_instance_id("grouped_forest_cover")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(widgets=forest_cover_widget, **grouped_forest_cover_params)
    .call()
)


# %% [markdown]
# ## Create Deforestation Dashboard

# %%
# parameters

gamm_dashboard_params = dict(
    warning=...,
)

# %%
# call the task


gamm_dashboard = (
    gather_dashboard.set_task_instance_id("gamm_dashboard")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        details=workflow_details,
        time_range=time_range,
        widgets=[grouped_forest_cover],
        groupers=groupers,
        **gamm_dashboard_params,
    )
    .call()
)
