# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


# ruff: noqa: E402

# %% [markdown]
# # Hansen Deforestation
# TODO: top level description

# %% [markdown]
# ## Imports

import os

from ecoscope_workflows_core.tasks.config import set_string_var as set_string_var
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import groupbykey as groupbykey
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.groupby import split_groups as split_groups
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.io import set_gee_connection as set_gee_connection
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.results import (
    merge_widget_views as merge_widget_views,
)
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_ext_custom.tasks.io import (
    persist_df_wrapper as persist_df_wrapper,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    create_polygon_layer_pydeck as create_polygon_layer_pydeck,
)
from ecoscope_workflows_ext_custom.tasks.results import draw_map as draw_map
from ecoscope_workflows_ext_custom.tasks.results import (
    merge_tile_layers as merge_tile_layers,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    set_base_maps_pydeck as set_base_maps_pydeck,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    load_spatial_features_group as load_spatial_features_group,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    draw_historic_timeseries as draw_historic_timeseries,
)
from ecoscope_workflows_ext_gamm_trend_analysis.tasks import (
    create_forest_layers as create_forest_layers,
)
from ecoscope_workflows_ext_gamm_trend_analysis.tasks import (
    extract_forest_cover_trends as extract_forest_cover_trends,
)
from ecoscope_workflows_ext_gamm_trend_analysis.tasks import (
    fit_gamm_model as fit_gamm_model,
)
from ecoscope_workflows_ext_gamm_trend_analysis.tasks import (
    predict_gamm_trends as predict_gamm_trends,
)
from ecoscope_workflows_ext_gamm_trend_analysis.tasks import (
    set_title_var as set_title_var,
)
from ecoscope_workflows_ext_gamm_trend_analysis.tasks import (
    set_tree_cover_threshold as set_tree_cover_threshold,
)

# %% [markdown]
# ## Set Workflow Details

# %%
# parameters

workflow_details_params = dict(
    name=...,
    description=...,
    image_url=...,
)

# %%
# call the task


workflow_details = (
    set_workflow_details.set_task_instance_id("workflow_details")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**workflow_details_params)
    .call()
)


# %% [markdown]
# ## Connect to Earth Engine

# %%
# parameters

gee_project_name_params = dict(
    data_source=...,
)

# %%
# call the task


gee_project_name = (
    set_gee_connection.set_task_instance_id("gee_project_name")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**gee_project_name_params)
    .call()
)


# %% [markdown]
# ## Time Range

# %%
# parameters

time_range_params = dict(
    since=...,
    until=...,
    timezone=...,
)

# %%
# call the task


time_range = (
    set_time_range.set_task_instance_id("time_range")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(time_format="%Y", **time_range_params)
    .call()
)


# %% [markdown]
# ## Hansen Dataset

# %%
# parameters

hansen_image_params = dict(
    var=...,
)

# %%
# call the task


hansen_image = (
    set_string_var.set_task_instance_id("hansen_image")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**hansen_image_params)
    .call()
)


# %% [markdown]
# ## Set Groupers

# %%
# parameters

groupers_params = dict(
    groupers=...,
)

# %%
# call the task


groupers = (
    set_groupers.set_task_instance_id("groupers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**groupers_params)
    .call()
)


# %% [markdown]
# ## Load Region of Interest

# %%
# parameters

roi_params = dict(
    config=...,
)

# %%
# call the task


roi = (
    load_spatial_features_group.set_task_instance_id("roi")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**roi_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

split_roi_groups_params = dict()

# %%
# call the task


split_roi_groups = (
    split_groups.set_task_instance_id("split_roi_groups")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(df=roi, groupers=groupers, **split_roi_groups_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

tree_cover_threshold_params = dict(
    threshold=...,
)

# %%
# call the task


tree_cover_threshold = (
    set_tree_cover_threshold.set_task_instance_id("tree_cover_threshold")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**tree_cover_threshold_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

forest_cover_trends_params = dict(
    scale=...,
    max_pixels=...,
)

# %%
# call the task


forest_cover_trends = (
    extract_forest_cover_trends.set_task_instance_id("forest_cover_trends")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        client=gee_project_name,
        time_range=time_range,
        image=hansen_image,
        tree_cover_threshold=tree_cover_threshold,
        **forest_cover_trends_params,
    )
    .mapvalues(argnames=["aoi"], argvalues=split_roi_groups)
)


# %% [markdown]
# ##

# %%
# parameters

persist_forest_cover_data_params = dict(
    filename=...,
)

# %%
# call the task


persist_forest_cover_data = (
    persist_df_wrapper.set_task_instance_id("persist_forest_cover_data")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        sanitize=True,
        filename_prefix="forest_cover",
        filetypes=["parquet"],
        **persist_forest_cover_data_params,
    )
    .mapvalues(argnames=["df"], argvalues=forest_cover_trends)
)


# %% [markdown]
# ##

# %%
# parameters

forest_layers_params = dict()

# %%
# call the task


forest_layers = (
    create_forest_layers.set_task_instance_id("forest_layers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        client=gee_project_name,
        time_range=time_range,
        image=hansen_image,
        tree_cover_threshold=tree_cover_threshold,
        opacity=1.0,
        **forest_layers_params,
    )
    .mapvalues(argnames=["aoi"], argvalues=split_roi_groups)
)


# %% [markdown]
# ## Base Maps

# %%
# parameters

base_map_defs_params = dict(
    base_maps=...,
)

# %%
# call the task


base_map_defs = (
    set_base_maps_pydeck.set_task_instance_id("base_map_defs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**base_map_defs_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

merged_forest_layers_params = dict()

# %%
# call the task


merged_forest_layers = (
    merge_tile_layers.set_task_instance_id("merged_forest_layers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(base_layers=base_map_defs, **merged_forest_layers_params)
    .mapvalues(argnames=["overlay"], argvalues=forest_layers)
)


# %% [markdown]
# ##

# %%
# parameters

roi_layer_params = dict()

# %%
# call the task


roi_layer = (
    create_polygon_layer_pydeck.set_task_instance_id("roi_layer")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        layer_style={
            "filled": False,
            "stroked": True,
            "get_line_color": [127, 201, 127, 255],
            "get_line_width": 1,
        },
        legend={
            "title": "ROI Boundary",
            "values": [{"label": "ROI Boundary", "color": "rgba(127, 201, 127, 1)"}],
        },
        **roi_layer_params,
    )
    .mapvalues(argnames=["geodataframe"], argvalues=split_roi_groups)
)


# %% [markdown]
# ##

# %%
# parameters

combined_forest_map_layers_params = dict()

# %%
# call the task


combined_forest_map_layers = (
    groupbykey.set_task_instance_id("combined_forest_map_layers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        iterables=[merged_forest_layers, roi_layer], **combined_forest_map_layers_params
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

forest_map_params = dict(
    widget_id=...,
)

# %%
# call the task


forest_map = (
    draw_map.set_task_instance_id("forest_map")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        title=None,
        static=False,
        max_zoom=20,
        view_state=None,
        legend_style=None,
        **forest_map_params,
    )
    .mapvalues(
        argnames=["tile_layers", "geo_layers"], argvalues=combined_forest_map_layers
    )
)


# %% [markdown]
# ##

# %%
# parameters

persist_forest_map_params = dict(
    filename=...,
)

# %%
# call the task


persist_forest_map = (
    persist_text.set_task_instance_id("persist_forest_map")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="map",
        text=forest_map,
        **persist_forest_map_params,
    )
    .mapvalues(argnames=["text"], argvalues=forest_map)
)


# %% [markdown]
# ##

# %%
# parameters

gamm_model_params = dict(
    metric=...,
    degree_of_freedom=...,
    degree=...,
    family=...,
)

# %%
# call the task


gamm_model = (
    fit_gamm_model.set_task_instance_id("gamm_model")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        time_column="year",
        value_column="survival_area",
        alpha=None,
        lower_bound=None,
        upper_bound=None,
        optimize_alpha=True,
        **gamm_model_params,
    )
    .mapvalues(argnames=["dataframe"], argvalues=forest_cover_trends)
)


# %% [markdown]
# ##

# %%
# parameters

trend_predictions_params = dict()

# %%
# call the task


trend_predictions = (
    predict_gamm_trends.set_task_instance_id("trend_predictions")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(time_values=None, include_ci=True, **trend_predictions_params)
    .mapvalues(argnames=["model_params"], argvalues=gamm_model)
)


# %% [markdown]
# ##

# %%
# parameters

persist_trend_data_params = dict(
    filename=...,
)

# %%
# call the task


persist_trend_data = (
    persist_df_wrapper.set_task_instance_id("persist_trend_data")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        sanitize=True,
        filename_prefix="trend_predictions",
        filetypes=["parquet"],
        **persist_trend_data_params,
    )
    .mapvalues(argnames=["df"], argvalues=trend_predictions)
)


# %% [markdown]
# ## Trend Chart

# %%
# parameters

forest_cover_chart_params = dict(
    widget_id=...,
)

# %%
# call the task


forest_cover_chart = (
    draw_historic_timeseries.set_task_instance_id("forest_cover_chart")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        current_value_column="y",
        time_column="time",
        current_value_title="Observed Trend",
        historic_min_column="ci_lower",
        historic_max_column="ci_upper",
        historic_mean_column="predicted",
        historic_mean_title="Trend Estimate",
        historic_band_title="Trend Confidence",
        layout_style={
            "xaxis": {"title": "Year"},
            "yaxis": {"title": "Survival Area (acres)"},
        },
        upper_lower_band_style={"mode": "lines", "line": {"color": "green"}},
        historic_mean_style=None,
        current_value_style=None,
        **forest_cover_chart_params,
    )
    .mapvalues(argnames=["dataframe"], argvalues=trend_predictions)
)


# %% [markdown]
# ##

# %%
# parameters

persist_forest_cover_params = dict(
    filename=...,
    filename_suffix=...,
)

# %%
# call the task


persist_forest_cover = (
    persist_text.set_task_instance_id("persist_forest_cover")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        text=forest_cover_chart,
        **persist_forest_cover_params,
    )
    .mapvalues(argnames=["text"], argvalues=forest_cover_chart)
)


# %% [markdown]
# ##

# %%
# parameters

map_widget_title_params = dict(
    title=...,
)

# %%
# call the task


map_widget_title = (
    set_title_var.set_task_instance_id("map_widget_title")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**map_widget_title_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

chart_widget_title_params = dict(
    title=...,
)

# %%
# call the task


chart_widget_title = (
    set_title_var.set_task_instance_id("chart_widget_title")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**chart_widget_title_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

forest_map_widget_params = dict()

# %%
# call the task


forest_map_widget = (
    create_map_widget_single_view.set_task_instance_id("forest_map_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(title=map_widget_title, **forest_map_widget_params)
    .map(argnames=["view", "data"], argvalues=persist_forest_map)
)


# %% [markdown]
# ##

# %%
# parameters

grouped_forest_map_params = dict()

# %%
# call the task


grouped_forest_map = (
    merge_widget_views.set_task_instance_id("grouped_forest_map")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(widgets=forest_map_widget, **grouped_forest_map_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

forest_cover_widget_params = dict()

# %%
# call the task


forest_cover_widget = (
    create_plot_widget_single_view.set_task_instance_id("forest_cover_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(title=chart_widget_title, **forest_cover_widget_params)
    .map(argnames=["view", "data"], argvalues=persist_forest_cover)
)


# %% [markdown]
# ##

# %%
# parameters

grouped_forest_cover_params = dict()

# %%
# call the task


grouped_forest_cover = (
    merge_widget_views.set_task_instance_id("grouped_forest_cover")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(widgets=forest_cover_widget, **grouped_forest_cover_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

gamm_dashboard_params = dict(
    warning=...,
)

# %%
# call the task


gamm_dashboard = (
    gather_dashboard.set_task_instance_id("gamm_dashboard")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        details=workflow_details,
        time_range=time_range,
        widgets=[grouped_forest_map, grouped_forest_cover],
        groupers=groupers,
        **gamm_dashboard_params,
    )
    .call()
)
