# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import json
import os

from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.groupby import split_groups as split_groups
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.io import set_gee_connection as set_gee_connection
from ecoscope_workflows_core.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.results import (
    merge_widget_views as merge_widget_views,
)
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    load_spatial_features_group as load_spatial_features_group,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    draw_historic_timeseries as draw_historic_timeseries,
)
from ecoscope_workflows_ext_gamm_trend_analysis.tasks import (
    extract_forest_cover_trends as extract_forest_cover_trends,
)
from ecoscope_workflows_ext_gamm_trend_analysis.tasks import (
    fit_gamm_model as fit_gamm_model,
)
from ecoscope_workflows_ext_gamm_trend_analysis.tasks import (
    predict_gamm_trends as predict_gamm_trends,
)

from ..params import Params


def main(params: Params):
    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    workflow_details = (
        set_workflow_details.validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("workflow_details") or {}))
        .call()
    )

    gee_project_name = (
        set_gee_connection.validate()
        .set_task_instance_id("gee_project_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("gee_project_name") or {}))
        .call()
    )

    time_range = (
        set_time_range.validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            time_format="%d %b %Y %H:%M:%S %Z",
            timezone={
                "label": "UTC",
                "tzCode": "UTC",
                "name": "Universal Coordinated Time",
                "utc": "+00:00",
            },
            since="2000-01-01T00:00:00.000Z",
            until="2023-12-31T23:59:59.000Z",
            **(params_dict.get("time_range") or {}),
        )
        .call()
    )

    groupers = (
        set_groupers.validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("groupers") or {}))
        .call()
    )

    roi = (
        load_spatial_features_group.validate()
        .set_task_instance_id("roi")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("roi") or {}))
        .call()
    )

    split_roi_groups = (
        split_groups.validate()
        .set_task_instance_id("split_roi_groups")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=roi, groupers=groupers, **(params_dict.get("split_roi_groups") or {})
        )
        .call()
    )

    forest_cover_trends = (
        extract_forest_cover_trends.validate()
        .set_task_instance_id("forest_cover_trends")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=gee_project_name, **(params_dict.get("forest_cover_trends") or {})
        )
        .mapvalues(argnames=["aoi"], argvalues=split_roi_groups)
    )

    gamm_model = (
        fit_gamm_model.validate()
        .set_task_instance_id("gamm_model")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            time_column="year",
            value_column="survival_area",
            alpha=None,
            lower_bound=None,
            upper_bound=None,
            optimize_alpha=True,
            **(params_dict.get("gamm_model") or {}),
        )
        .mapvalues(argnames=["dataframe"], argvalues=forest_cover_trends)
    )

    trend_predictions = (
        predict_gamm_trends.validate()
        .set_task_instance_id("trend_predictions")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            time_values=None,
            include_ci=True,
            **(params_dict.get("trend_predictions") or {}),
        )
        .mapvalues(argnames=["model_params"], argvalues=gamm_model)
    )

    forest_cover_chart = (
        draw_historic_timeseries.validate()
        .set_task_instance_id("forest_cover_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=trend_predictions,
            current_value_column="y",
            time_column="time",
            current_value_title="Observed Survival Area",
            historic_min_column="ci_lower",
            historic_max_column="ci_upper",
            historic_mean_column="predicted",
            historic_mean_title="GAM Mean",
            historic_band_title="GAM 95% CI",
            layout_style={
                "title": "Forest survival area trend (GAM)",
                "xaxis": {"title": "Year"},
                "yaxis": {"title": "Survival Area (acres)"},
            },
            upper_lower_band_style={"mode": "lines", "line": {"color": "green"}},
            historic_mean_style=None,
            current_value_style=None,
            **(params_dict.get("forest_cover_chart") or {}),
        )
        .mapvalues(argnames=["dataframe"], argvalues=trend_predictions)
    )

    persist_forest_cover = (
        persist_text.validate()
        .set_task_instance_id("persist_forest_cover")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=forest_cover_chart,
            **(params_dict.get("persist_forest_cover") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=forest_cover_chart)
    )

    forest_cover_widget = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("forest_cover_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Forest Cover Trend Chart",
            **(params_dict.get("forest_cover_widget") or {}),
        )
        .map(argnames=["view", "data"], argvalues=persist_forest_cover)
    )

    grouped_forest_cover = (
        merge_widget_views.validate()
        .set_task_instance_id("grouped_forest_cover")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=forest_cover_widget,
            **(params_dict.get("grouped_forest_cover") or {}),
        )
        .call()
    )

    gamm_dashboard = (
        gather_dashboard.validate()
        .set_task_instance_id("gamm_dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            time_range=time_range,
            widgets=[grouped_forest_cover],
            groupers=groupers,
            **(params_dict.get("gamm_dashboard") or {}),
        )
        .call()
    )

    return gamm_dashboard
