# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import os
import warnings  # 🧪
from typing import Any

from ecoscope.platform.tasks.config import set_string_var as set_string_var
from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.groupby import set_groupers as set_groupers
from ecoscope.platform.tasks.io import set_gee_connection as set_gee_connection
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from wt_contracts import validate as _validate
from wt_task import task
from wt_task.testing import create_func_magicmock  # 🧪

from .. import metadata as _metadata

load_spatial_features_group = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="load_spatial_features_group",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.analysis import (
    create_forest_layers as create_forest_layers,
)
from ecoscope.platform.tasks.analysis import (
    extract_forest_cover_trends as extract_forest_cover_trends,
)
from ecoscope.platform.tasks.analysis import fit_trend_model as fit_trend_model
from ecoscope.platform.tasks.analysis import predict_trend_model as predict_trend_model
from ecoscope.platform.tasks.analysis import set_trend_model as set_trend_model
from ecoscope.platform.tasks.analysis._trend_analysis import (
    is_gamm_trend_model as is_gamm_trend_model,
)
from ecoscope.platform.tasks.analysis._trend_analysis import (
    is_not_gamm_trend_model as is_not_gamm_trend_model,
)
from ecoscope.platform.tasks.config import set_float_var as set_float_var
from ecoscope.platform.tasks.groupby import groupbykey as groupbykey
from ecoscope.platform.tasks.groupby import (
    groupbykey_passthrough_skip as groupbykey_passthrough_skip,
)
from ecoscope.platform.tasks.groupby import split_groups as split_groups
from ecoscope.platform.tasks.io import persist_df_wrapper as persist_df_wrapper
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_polygon_layer_pydeck as create_polygon_layer_pydeck,
)
from ecoscope.platform.tasks.results import (
    draw_historic_timeseries as draw_historic_timeseries,
)
from ecoscope.platform.tasks.results import draw_map as draw_map
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.results import merge_tile_layers as merge_tile_layers
from ecoscope.platform.tasks.results import merge_widget_views as merge_widget_views
from ecoscope.platform.tasks.results import set_base_maps as set_base_maps
from ecoscope.platform.tasks.skip import never as never
from ecoscope.platform.tasks.transformation import (
    concat_dataframes as concat_dataframes,
)


def main(params: dict[str, Any], validate_params_schema: bool = True):
    warnings.warn("This test script should not be used in production!")  # 🧪

    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    gee_project_name = (
        task(set_gee_connection)
        .validate()
        .set_task_instance_id("gee_project_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("gee_project_name") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_format="%Y", **(params.get("time_range") or {}))
        .call()
    )

    hansen_image = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("hansen_image")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("hansen_image") or {}))
        .call()
    )

    groupers = (
        task(set_groupers)
        .validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("groupers") or {}))
        .call()
    )

    roi = (
        task(load_spatial_features_group)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("roi")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("roi") or {}))
        .call()
    )

    split_roi_groups = (
        task(split_groups)
        .validate()
        .set_task_instance_id("split_roi_groups")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(df=roi, groupers=groupers, **(params.get("split_roi_groups") or {}))
        .call()
    )

    tree_cover_threshold = (
        task(set_float_var)
        .validate()
        .set_task_instance_id("tree_cover_threshold")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("tree_cover_threshold") or {}))
        .call()
    )

    forest_cover_trends = (
        task(extract_forest_cover_trends)
        .validate()
        .set_task_instance_id("forest_cover_trends")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=gee_project_name,
            time_range=time_range,
            image=hansen_image,
            tree_cover_threshold=tree_cover_threshold,
            **(params.get("forest_cover_trends") or {}),
        )
        .mapvalues(argnames=["aoi"], argvalues=split_roi_groups)
    )

    persist_forest_cover_data = (
        task(persist_df_wrapper)
        .validate()
        .set_task_instance_id("persist_forest_cover_data")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            sanitize=True,
            filename_prefix="forest_cover",
            filetypes=["parquet"],
            **(params.get("persist_forest_cover_data") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=forest_cover_trends)
    )

    forest_layers = (
        task(create_forest_layers)
        .validate()
        .set_task_instance_id("forest_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=gee_project_name,
            time_range=time_range,
            image=hansen_image,
            tree_cover_threshold=tree_cover_threshold,
            opacity=1.0,
            **(params.get("forest_layers") or {}),
        )
        .mapvalues(argnames=["aoi"], argvalues=split_roi_groups)
    )

    base_map_defs = (
        task(set_base_maps)
        .validate()
        .set_task_instance_id("base_map_defs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("base_map_defs") or {}))
        .call()
    )

    merged_forest_layers = (
        task(merge_tile_layers)
        .validate()
        .set_task_instance_id("merged_forest_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            base_layers=base_map_defs, **(params.get("merged_forest_layers") or {})
        )
        .mapvalues(argnames=["overlay"], argvalues=forest_layers)
    )

    roi_layer = (
        task(create_polygon_layer_pydeck)
        .validate()
        .set_task_instance_id("roi_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            data_url=None,
            layer_style={
                "filled": False,
                "stroked": True,
                "get_line_color": [127, 201, 127, 255],
                "get_line_width": 1,
            },
            legend={
                "title": "ROI Boundary",
                "values": [
                    {"label": "ROI Boundary", "color": "rgba(127, 201, 127, 1)"}
                ],
            },
            **(params.get("roi_layer") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=split_roi_groups)
    )

    combined_forest_map_layers = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("combined_forest_map_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[merged_forest_layers, roi_layer],
            **(params.get("combined_forest_map_layers") or {}),
        )
        .call()
    )

    forest_map = (
        task(draw_map)
        .validate()
        .set_task_instance_id("forest_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title=None,
            static=False,
            output_type="html",
            max_zoom=20,
            view_state=None,
            legend_style=None,
            **(params.get("forest_map") or {}),
        )
        .mapvalues(
            argnames=["tile_layers", "geo_layers"], argvalues=combined_forest_map_layers
        )
    )

    persist_forest_map = (
        task(persist_text)
        .validate()
        .set_task_instance_id("persist_forest_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="map",
            text=forest_map,
            **(params.get("persist_forest_map") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=forest_map)
    )

    trend_model = (
        task(set_trend_model)
        .validate()
        .set_task_instance_id("trend_model")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("trend_model") or {}))
        .call()
    )

    trend_fit = (
        task(fit_trend_model)
        .validate()
        .set_task_instance_id("trend_fit")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                is_gamm_trend_model,
            ],
            unpack_depth=1,
        )
        .partial(
            time_column="year",
            value_column="cumsum_loss_pct",
            model=trend_model,
            **(params.get("trend_fit") or {}),
        )
        .mapvalues(argnames=["dataframe"], argvalues=forest_cover_trends)
    )

    trend_predictions = (
        task(predict_trend_model)
        .validate()
        .set_task_instance_id("trend_predictions")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            time_column="time",
            value_column="value",
            time_values=None,
            include_ci=True,
            **(params.get("trend_predictions") or {}),
        )
        .mapvalues(argnames=["model_params"], argvalues=trend_fit)
    )

    forest_cover_trends_combined = (
        task(concat_dataframes)
        .validate()
        .set_task_instance_id("forest_cover_trends_combined")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dfs=forest_cover_trends,
            ensure_columns=[
                "year",
                "loss_area",
                "cumsum_loss_area",
                "survival_area",
                "cumsum_loss_pct",
                "name",
            ],
            reset_index=True,
            **(params.get("forest_cover_trends_combined") or {}),
        )
        .call()
    )

    trend_fit_combined = (
        task(fit_trend_model)
        .validate()
        .set_task_instance_id("trend_fit_combined")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                is_not_gamm_trend_model,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=forest_cover_trends_combined,
            time_column="year",
            value_column="cumsum_loss_pct",
            model=trend_model,
            **(params.get("trend_fit_combined") or {}),
        )
        .call()
    )

    trend_predictions_gamm = (
        task(predict_trend_model)
        .validate()
        .set_task_instance_id("trend_predictions_gamm")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            model_params=trend_fit_combined,
            time_column="year",
            value_column="cumsum_loss_pct",
            time_values=None,
            include_ci=True,
            **(params.get("trend_predictions_gamm") or {}),
        )
        .mapvalues(argnames=["dataframe"], argvalues=forest_cover_trends)
    )

    trend_predictions_merged = (
        task(groupbykey_passthrough_skip)
        .validate()
        .set_task_instance_id("trend_predictions_merged")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[trend_predictions, trend_predictions_gamm],
            **(params.get("trend_predictions_merged") or {}),
        )
        .call()
    )

    trend_predictions_final = (
        task(concat_dataframes)
        .validate()
        .set_task_instance_id("trend_predictions_final")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            ensure_columns=[],
            reset_index=True,
            **(params.get("trend_predictions_final") or {}),
        )
        .mapvalues(argnames=["dfs"], argvalues=trend_predictions_merged)
    )

    persist_trend_data = (
        task(persist_df_wrapper)
        .validate()
        .set_task_instance_id("persist_trend_data")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            sanitize=True,
            filename_prefix="trend_predictions",
            filetypes=["parquet"],
            **(params.get("persist_trend_data") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=trend_predictions_final)
    )

    forest_cover_chart = (
        task(draw_historic_timeseries)
        .validate()
        .set_task_instance_id("forest_cover_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            current_value_column="y",
            time_column="time",
            current_value_title="Observed Trend",
            historic_min_column="ci_lower",
            historic_max_column="ci_upper",
            historic_mean_column="predicted",
            historic_mean_title="Trend Estimate",
            historic_band_title="Trend Confidence",
            layout_style={
                "xaxis": {"title": "Year"},
                "yaxis": {"title": "Cumulative Forest Loss (% of Original)"},
            },
            upper_lower_band_style={"mode": "lines", "line": {"color": "green"}},
            historic_mean_style=None,
            current_value_style=None,
            **(params.get("forest_cover_chart") or {}),
        )
        .mapvalues(argnames=["dataframe"], argvalues=trend_predictions_final)
    )

    persist_forest_cover = (
        task(persist_text)
        .validate()
        .set_task_instance_id("persist_forest_cover")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=forest_cover_chart,
            **(params.get("persist_forest_cover") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=forest_cover_chart)
    )

    map_widget_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("map_widget_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("map_widget_title") or {}))
        .call()
    )

    chart_widget_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("chart_widget_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("chart_widget_title") or {}))
        .call()
    )

    forest_map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("forest_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(title=map_widget_title, **(params.get("forest_map_widget") or {}))
        .map(argnames=["view", "data"], argvalues=persist_forest_map)
    )

    grouped_forest_map = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("grouped_forest_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(widgets=forest_map_widget, **(params.get("grouped_forest_map") or {}))
        .call()
    )

    forest_cover_widget = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("forest_cover_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(title=chart_widget_title, **(params.get("forest_cover_widget") or {}))
        .map(argnames=["view", "data"], argvalues=persist_forest_cover)
    )

    grouped_forest_cover = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("grouped_forest_cover")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=forest_cover_widget, **(params.get("grouped_forest_cover") or {})
        )
        .call()
    )

    gamm_dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("gamm_dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            time_range=time_range,
            widgets=[grouped_forest_map, grouped_forest_cover],
            groupers=groupers,
            **(params.get("gamm_dashboard") or {}),
        )
        .call()
    )

    return gamm_dashboard
