# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import json
import os

from ecoscope_workflows_core.tasks.config import set_string_var as set_string_var
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import groupbykey as groupbykey
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.groupby import split_groups as split_groups
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.io import set_gee_connection as set_gee_connection
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.results import (
    merge_widget_views as merge_widget_views,
)
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_ext_custom.tasks.io import (
    persist_df_wrapper as persist_df_wrapper,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    create_polygon_layer_pydeck as create_polygon_layer_pydeck,
)
from ecoscope_workflows_ext_custom.tasks.results import draw_map as draw_map
from ecoscope_workflows_ext_custom.tasks.results import (
    merge_tile_layers as merge_tile_layers,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    set_base_maps_pydeck as set_base_maps_pydeck,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    load_spatial_features_group as load_spatial_features_group,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    draw_historic_timeseries as draw_historic_timeseries,
)
from ecoscope_workflows_ext_gamm_trend_analysis.tasks import (
    create_forest_layers as create_forest_layers,
)
from ecoscope_workflows_ext_gamm_trend_analysis.tasks import (
    extract_forest_cover_trends as extract_forest_cover_trends,
)
from ecoscope_workflows_ext_gamm_trend_analysis.tasks import (
    fit_gamm_model as fit_gamm_model,
)
from ecoscope_workflows_ext_gamm_trend_analysis.tasks import (
    predict_gamm_trends as predict_gamm_trends,
)
from ecoscope_workflows_ext_gamm_trend_analysis.tasks import (
    set_title_var as set_title_var,
)
from ecoscope_workflows_ext_gamm_trend_analysis.tasks import (
    set_tree_cover_threshold as set_tree_cover_threshold,
)

from ..params import Params


def main(params: Params):
    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    workflow_details = (
        set_workflow_details.validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("workflow_details") or {}))
        .call()
    )

    gee_project_name = (
        set_gee_connection.validate()
        .set_task_instance_id("gee_project_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("gee_project_name") or {}))
        .call()
    )

    time_range = (
        set_time_range.validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_format="%Y", **(params_dict.get("time_range") or {}))
        .call()
    )

    hansen_image = (
        set_string_var.validate()
        .set_task_instance_id("hansen_image")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("hansen_image") or {}))
        .call()
    )

    groupers = (
        set_groupers.validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("groupers") or {}))
        .call()
    )

    roi = (
        load_spatial_features_group.validate()
        .set_task_instance_id("roi")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("roi") or {}))
        .call()
    )

    split_roi_groups = (
        split_groups.validate()
        .set_task_instance_id("split_roi_groups")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=roi, groupers=groupers, **(params_dict.get("split_roi_groups") or {})
        )
        .call()
    )

    tree_cover_threshold = (
        set_tree_cover_threshold.validate()
        .set_task_instance_id("tree_cover_threshold")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("tree_cover_threshold") or {}))
        .call()
    )

    forest_cover_trends = (
        extract_forest_cover_trends.validate()
        .set_task_instance_id("forest_cover_trends")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=gee_project_name,
            time_range=time_range,
            image=hansen_image,
            tree_cover_threshold=tree_cover_threshold,
            **(params_dict.get("forest_cover_trends") or {}),
        )
        .mapvalues(argnames=["aoi"], argvalues=split_roi_groups)
    )

    persist_forest_cover_data = (
        persist_df_wrapper.validate()
        .set_task_instance_id("persist_forest_cover_data")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            sanitize=True,
            filename_prefix="forest_cover",
            filetypes=["parquet"],
            **(params_dict.get("persist_forest_cover_data") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=forest_cover_trends)
    )

    forest_layers = (
        create_forest_layers.validate()
        .set_task_instance_id("forest_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=gee_project_name,
            time_range=time_range,
            image=hansen_image,
            tree_cover_threshold=tree_cover_threshold,
            opacity=1.0,
            **(params_dict.get("forest_layers") or {}),
        )
        .mapvalues(argnames=["aoi"], argvalues=split_roi_groups)
    )

    base_map_defs = (
        set_base_maps_pydeck.validate()
        .set_task_instance_id("base_map_defs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("base_map_defs") or {}))
        .call()
    )

    merged_forest_layers = (
        merge_tile_layers.validate()
        .set_task_instance_id("merged_forest_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            base_layers=base_map_defs, **(params_dict.get("merged_forest_layers") or {})
        )
        .mapvalues(argnames=["overlay"], argvalues=forest_layers)
    )

    roi_layer = (
        create_polygon_layer_pydeck.validate()
        .set_task_instance_id("roi_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "filled": False,
                "stroked": True,
                "get_line_color": [127, 201, 127, 255],
                "get_line_width": 1,
            },
            legend={
                "title": "ROI Boundary",
                "values": [
                    {"label": "ROI Boundary", "color": "rgba(127, 201, 127, 1)"}
                ],
            },
            **(params_dict.get("roi_layer") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=split_roi_groups)
    )

    combined_forest_map_layers = (
        groupbykey.validate()
        .set_task_instance_id("combined_forest_map_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[merged_forest_layers, roi_layer],
            **(params_dict.get("combined_forest_map_layers") or {}),
        )
        .call()
    )

    forest_map = (
        draw_map.validate()
        .set_task_instance_id("forest_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title=None,
            static=False,
            max_zoom=20,
            view_state=None,
            legend_style=None,
            **(params_dict.get("forest_map") or {}),
        )
        .mapvalues(
            argnames=["tile_layers", "geo_layers"], argvalues=combined_forest_map_layers
        )
    )

    persist_forest_map = (
        persist_text.validate()
        .set_task_instance_id("persist_forest_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="map",
            text=forest_map,
            **(params_dict.get("persist_forest_map") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=forest_map)
    )

    gamm_model = (
        fit_gamm_model.validate()
        .set_task_instance_id("gamm_model")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            time_column="year",
            value_column="survival_area",
            alpha=None,
            lower_bound=None,
            upper_bound=None,
            optimize_alpha=True,
            **(params_dict.get("gamm_model") or {}),
        )
        .mapvalues(argnames=["dataframe"], argvalues=forest_cover_trends)
    )

    trend_predictions = (
        predict_gamm_trends.validate()
        .set_task_instance_id("trend_predictions")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            time_values=None,
            include_ci=True,
            **(params_dict.get("trend_predictions") or {}),
        )
        .mapvalues(argnames=["model_params"], argvalues=gamm_model)
    )

    persist_trend_data = (
        persist_df_wrapper.validate()
        .set_task_instance_id("persist_trend_data")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            sanitize=True,
            filename_prefix="trend_predictions",
            filetypes=["parquet"],
            **(params_dict.get("persist_trend_data") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=trend_predictions)
    )

    forest_cover_chart = (
        draw_historic_timeseries.validate()
        .set_task_instance_id("forest_cover_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            current_value_column="y",
            time_column="time",
            current_value_title="Observed Trend",
            historic_min_column="ci_lower",
            historic_max_column="ci_upper",
            historic_mean_column="predicted",
            historic_mean_title="Trend Estimate",
            historic_band_title="Trend Confidence",
            layout_style={
                "xaxis": {"title": "Year"},
                "yaxis": {"title": "Survival Area (acres)"},
            },
            upper_lower_band_style={"mode": "lines", "line": {"color": "green"}},
            historic_mean_style=None,
            current_value_style=None,
            **(params_dict.get("forest_cover_chart") or {}),
        )
        .mapvalues(argnames=["dataframe"], argvalues=trend_predictions)
    )

    persist_forest_cover = (
        persist_text.validate()
        .set_task_instance_id("persist_forest_cover")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=forest_cover_chart,
            **(params_dict.get("persist_forest_cover") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=forest_cover_chart)
    )

    map_widget_title = (
        set_title_var.validate()
        .set_task_instance_id("map_widget_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("map_widget_title") or {}))
        .call()
    )

    chart_widget_title = (
        set_title_var.validate()
        .set_task_instance_id("chart_widget_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params_dict.get("chart_widget_title") or {}))
        .call()
    )

    forest_map_widget = (
        create_map_widget_single_view.validate()
        .set_task_instance_id("forest_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(title=map_widget_title, **(params_dict.get("forest_map_widget") or {}))
        .map(argnames=["view", "data"], argvalues=persist_forest_map)
    )

    grouped_forest_map = (
        merge_widget_views.validate()
        .set_task_instance_id("grouped_forest_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=forest_map_widget, **(params_dict.get("grouped_forest_map") or {})
        )
        .call()
    )

    forest_cover_widget = (
        create_plot_widget_single_view.validate()
        .set_task_instance_id("forest_cover_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title=chart_widget_title, **(params_dict.get("forest_cover_widget") or {})
        )
        .map(argnames=["view", "data"], argvalues=persist_forest_cover)
    )

    grouped_forest_cover = (
        merge_widget_views.validate()
        .set_task_instance_id("grouped_forest_cover")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=forest_cover_widget,
            **(params_dict.get("grouped_forest_cover") or {}),
        )
        .call()
    )

    gamm_dashboard = (
        gather_dashboard.validate()
        .set_task_instance_id("gamm_dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            time_range=time_range,
            widgets=[grouped_forest_map, grouped_forest_cover],
            groupers=groupers,
            **(params_dict.get("gamm_dashboard") or {}),
        )
        .call()
    )

    return gamm_dashboard
