# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

# ruff: noqa: E402

"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import json
import os
import warnings  # 🧪

from ecoscope_workflows_core.graph import DependsOn, Graph, Node
from ecoscope_workflows_core.tasks.config import set_string_var as set_string_var
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.io import set_gee_connection as set_gee_connection
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.testing import create_task_magicmock  # 🧪

load_spatial_features_group = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_ecoscope.tasks.io",  # 🧪
    func_name="load_spatial_features_group",  # 🧪
)  # 🧪
from ecoscope_workflows_core.tasks.groupby import groupbykey as groupbykey
from ecoscope_workflows_core.tasks.groupby import split_groups as split_groups
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.results import (
    merge_widget_views as merge_widget_views,
)
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_ext_custom.tasks.io import (
    persist_df_wrapper as persist_df_wrapper,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    create_polygon_layer_pydeck as create_polygon_layer_pydeck,
)
from ecoscope_workflows_ext_custom.tasks.results import draw_map as draw_map
from ecoscope_workflows_ext_custom.tasks.results import (
    merge_tile_layers as merge_tile_layers,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    set_base_maps_pydeck as set_base_maps_pydeck,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    draw_historic_timeseries as draw_historic_timeseries,
)
from ecoscope_workflows_ext_gamm_trend_analysis.tasks import (
    create_forest_layers as create_forest_layers,
)
from ecoscope_workflows_ext_gamm_trend_analysis.tasks import (
    extract_forest_cover_trends as extract_forest_cover_trends,
)
from ecoscope_workflows_ext_gamm_trend_analysis.tasks import (
    fit_gamm_model as fit_gamm_model,
)
from ecoscope_workflows_ext_gamm_trend_analysis.tasks import (
    predict_gamm_trends as predict_gamm_trends,
)
from ecoscope_workflows_ext_gamm_trend_analysis.tasks import (
    set_title_var as set_title_var,
)
from ecoscope_workflows_ext_gamm_trend_analysis.tasks import (
    set_tree_cover_threshold as set_tree_cover_threshold,
)

from ..params import Params


def main(params: Params):
    warnings.warn("This test script should not be used in production!")  # 🧪

    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    dependencies = {
        "workflow_details": [],
        "gee_project_name": [],
        "time_range": [],
        "hansen_image": [],
        "groupers": [],
        "roi": [],
        "split_roi_groups": ["roi", "groupers"],
        "tree_cover_threshold": [],
        "forest_cover_trends": [
            "gee_project_name",
            "time_range",
            "hansen_image",
            "tree_cover_threshold",
            "split_roi_groups",
        ],
        "persist_forest_cover_data": ["forest_cover_trends"],
        "forest_layers": [
            "gee_project_name",
            "time_range",
            "hansen_image",
            "tree_cover_threshold",
            "split_roi_groups",
        ],
        "base_map_defs": [],
        "merged_forest_layers": ["base_map_defs", "forest_layers"],
        "roi_layer": ["split_roi_groups"],
        "combined_forest_map_layers": ["merged_forest_layers", "roi_layer"],
        "forest_map": ["combined_forest_map_layers"],
        "persist_forest_map": ["forest_map", "forest_map"],
        "gamm_model": ["forest_cover_trends"],
        "trend_predictions": ["gamm_model"],
        "persist_trend_data": ["trend_predictions"],
        "forest_cover_chart": ["trend_predictions"],
        "persist_forest_cover": ["forest_cover_chart", "forest_cover_chart"],
        "map_widget_title": [],
        "chart_widget_title": [],
        "forest_map_widget": ["map_widget_title", "persist_forest_map"],
        "grouped_forest_map": ["forest_map_widget"],
        "forest_cover_widget": ["chart_widget_title", "persist_forest_cover"],
        "grouped_forest_cover": ["forest_cover_widget"],
        "gamm_dashboard": [
            "workflow_details",
            "time_range",
            "grouped_forest_map",
            "grouped_forest_cover",
            "groupers",
        ],
    }

    nodes = {
        "workflow_details": Node(
            async_task=set_workflow_details.validate()
            .set_task_instance_id("workflow_details")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("workflow_details") or {}),
            method="call",
        ),
        "gee_project_name": Node(
            async_task=set_gee_connection.validate()
            .set_task_instance_id("gee_project_name")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("gee_project_name") or {}),
            method="call",
        ),
        "time_range": Node(
            async_task=set_time_range.validate()
            .set_task_instance_id("time_range")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "time_format": "%Y",
            }
            | (params_dict.get("time_range") or {}),
            method="call",
        ),
        "hansen_image": Node(
            async_task=set_string_var.validate()
            .set_task_instance_id("hansen_image")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("hansen_image") or {}),
            method="call",
        ),
        "groupers": Node(
            async_task=set_groupers.validate()
            .set_task_instance_id("groupers")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("groupers") or {}),
            method="call",
        ),
        "roi": Node(
            async_task=load_spatial_features_group.validate()
            .set_task_instance_id("roi")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("roi") or {}),
            method="call",
        ),
        "split_roi_groups": Node(
            async_task=split_groups.validate()
            .set_task_instance_id("split_roi_groups")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("roi"),
                "groupers": DependsOn("groupers"),
            }
            | (params_dict.get("split_roi_groups") or {}),
            method="call",
        ),
        "tree_cover_threshold": Node(
            async_task=set_tree_cover_threshold.validate()
            .set_task_instance_id("tree_cover_threshold")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("tree_cover_threshold") or {}),
            method="call",
        ),
        "forest_cover_trends": Node(
            async_task=extract_forest_cover_trends.validate()
            .set_task_instance_id("forest_cover_trends")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "client": DependsOn("gee_project_name"),
                "time_range": DependsOn("time_range"),
                "image": DependsOn("hansen_image"),
                "tree_cover_threshold": DependsOn("tree_cover_threshold"),
            }
            | (params_dict.get("forest_cover_trends") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["aoi"],
                "argvalues": DependsOn("split_roi_groups"),
            },
        ),
        "persist_forest_cover_data": Node(
            async_task=persist_df_wrapper.validate()
            .set_task_instance_id("persist_forest_cover_data")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "sanitize": True,
                "filename_prefix": "forest_cover",
                "filetypes": [
                    "parquet",
                ],
            }
            | (params_dict.get("persist_forest_cover_data") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("forest_cover_trends"),
            },
        ),
        "forest_layers": Node(
            async_task=create_forest_layers.validate()
            .set_task_instance_id("forest_layers")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "client": DependsOn("gee_project_name"),
                "time_range": DependsOn("time_range"),
                "image": DependsOn("hansen_image"),
                "tree_cover_threshold": DependsOn("tree_cover_threshold"),
                "opacity": 1.0,
            }
            | (params_dict.get("forest_layers") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["aoi"],
                "argvalues": DependsOn("split_roi_groups"),
            },
        ),
        "base_map_defs": Node(
            async_task=set_base_maps_pydeck.validate()
            .set_task_instance_id("base_map_defs")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("base_map_defs") or {}),
            method="call",
        ),
        "merged_forest_layers": Node(
            async_task=merge_tile_layers.validate()
            .set_task_instance_id("merged_forest_layers")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "base_layers": DependsOn("base_map_defs"),
            }
            | (params_dict.get("merged_forest_layers") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["overlay"],
                "argvalues": DependsOn("forest_layers"),
            },
        ),
        "roi_layer": Node(
            async_task=create_polygon_layer_pydeck.validate()
            .set_task_instance_id("roi_layer")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "layer_style": {
                    "filled": False,
                    "stroked": True,
                    "get_line_color": [
                        127,
                        201,
                        127,
                        255,
                    ],
                    "get_line_width": 1,
                },
                "legend": {
                    "title": "ROI Boundary",
                    "values": [
                        {
                            "label": "ROI Boundary",
                            "color": "rgba(127, 201, 127, 1)",
                        },
                    ],
                },
            }
            | (params_dict.get("roi_layer") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geodataframe"],
                "argvalues": DependsOn("split_roi_groups"),
            },
        ),
        "combined_forest_map_layers": Node(
            async_task=groupbykey.validate()
            .set_task_instance_id("combined_forest_map_layers")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "iterables": [
                    DependsOn("merged_forest_layers"),
                    DependsOn("roi_layer"),
                ],
            }
            | (params_dict.get("combined_forest_map_layers") or {}),
            method="call",
        ),
        "forest_map": Node(
            async_task=draw_map.validate()
            .set_task_instance_id("forest_map")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": None,
                "static": False,
                "max_zoom": 20,
                "view_state": None,
                "legend_style": None,
            }
            | (params_dict.get("forest_map") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["tile_layers", "geo_layers"],
                "argvalues": DependsOn("combined_forest_map_layers"),
            },
        ),
        "persist_forest_map": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_forest_map")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "map",
                "text": DependsOn("forest_map"),
            }
            | (params_dict.get("persist_forest_map") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["text"],
                "argvalues": DependsOn("forest_map"),
            },
        ),
        "gamm_model": Node(
            async_task=fit_gamm_model.validate()
            .set_task_instance_id("gamm_model")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "time_column": "year",
                "value_column": "survival_area",
                "alpha": None,
                "lower_bound": None,
                "upper_bound": None,
                "optimize_alpha": True,
            }
            | (params_dict.get("gamm_model") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["dataframe"],
                "argvalues": DependsOn("forest_cover_trends"),
            },
        ),
        "trend_predictions": Node(
            async_task=predict_gamm_trends.validate()
            .set_task_instance_id("trend_predictions")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "time_values": None,
                "include_ci": True,
            }
            | (params_dict.get("trend_predictions") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["model_params"],
                "argvalues": DependsOn("gamm_model"),
            },
        ),
        "persist_trend_data": Node(
            async_task=persist_df_wrapper.validate()
            .set_task_instance_id("persist_trend_data")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "sanitize": True,
                "filename_prefix": "trend_predictions",
                "filetypes": [
                    "parquet",
                ],
            }
            | (params_dict.get("persist_trend_data") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("trend_predictions"),
            },
        ),
        "forest_cover_chart": Node(
            async_task=draw_historic_timeseries.validate()
            .set_task_instance_id("forest_cover_chart")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "current_value_column": "y",
                "time_column": "time",
                "current_value_title": "Observed Trend",
                "historic_min_column": "ci_lower",
                "historic_max_column": "ci_upper",
                "historic_mean_column": "predicted",
                "historic_mean_title": "Trend Estimate",
                "historic_band_title": "Trend Confidence",
                "layout_style": {
                    "xaxis": {
                        "title": "Year",
                    },
                    "yaxis": {
                        "title": "Survival Area (acres)",
                    },
                },
                "upper_lower_band_style": {
                    "mode": "lines",
                    "line": {
                        "color": "green",
                    },
                },
                "historic_mean_style": None,
                "current_value_style": None,
            }
            | (params_dict.get("forest_cover_chart") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["dataframe"],
                "argvalues": DependsOn("trend_predictions"),
            },
        ),
        "persist_forest_cover": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_forest_cover")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "text": DependsOn("forest_cover_chart"),
            }
            | (params_dict.get("persist_forest_cover") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["text"],
                "argvalues": DependsOn("forest_cover_chart"),
            },
        ),
        "map_widget_title": Node(
            async_task=set_title_var.validate()
            .set_task_instance_id("map_widget_title")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("map_widget_title") or {}),
            method="call",
        ),
        "chart_widget_title": Node(
            async_task=set_title_var.validate()
            .set_task_instance_id("chart_widget_title")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("chart_widget_title") or {}),
            method="call",
        ),
        "forest_map_widget": Node(
            async_task=create_map_widget_single_view.validate()
            .set_task_instance_id("forest_map_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": DependsOn("map_widget_title"),
            }
            | (params_dict.get("forest_map_widget") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("persist_forest_map"),
            },
        ),
        "grouped_forest_map": Node(
            async_task=merge_widget_views.validate()
            .set_task_instance_id("grouped_forest_map")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("forest_map_widget"),
            }
            | (params_dict.get("grouped_forest_map") or {}),
            method="call",
        ),
        "forest_cover_widget": Node(
            async_task=create_plot_widget_single_view.validate()
            .set_task_instance_id("forest_cover_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": DependsOn("chart_widget_title"),
            }
            | (params_dict.get("forest_cover_widget") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("persist_forest_cover"),
            },
        ),
        "grouped_forest_cover": Node(
            async_task=merge_widget_views.validate()
            .set_task_instance_id("grouped_forest_cover")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("forest_cover_widget"),
            }
            | (params_dict.get("grouped_forest_cover") or {}),
            method="call",
        ),
        "gamm_dashboard": Node(
            async_task=gather_dashboard.validate()
            .set_task_instance_id("gamm_dashboard")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "details": DependsOn("workflow_details"),
                "time_range": DependsOn("time_range"),
                "widgets": [
                    DependsOn("grouped_forest_map"),
                    DependsOn("grouped_forest_cover"),
                ],
                "groupers": DependsOn("groupers"),
            }
            | (params_dict.get("gamm_dashboard") or {}),
            method="call",
        ),
    }
    graph = Graph(dependencies=dependencies, nodes=nodes)
    results = graph.execute()
    return results
