# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import json
import os

from ecoscope_workflows_core.graph import DependsOn, Graph, Node
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.groupby import split_groups as split_groups
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.io import set_gee_connection as set_gee_connection
from ecoscope_workflows_core.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.results import (
    merge_widget_views as merge_widget_views,
)
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    load_spatial_features_group as load_spatial_features_group,
)
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    draw_historic_timeseries as draw_historic_timeseries,
)
from ecoscope_workflows_ext_gamm_trend_analysis.tasks import (
    extract_forest_cover_trends as extract_forest_cover_trends,
)
from ecoscope_workflows_ext_gamm_trend_analysis.tasks import (
    fit_gamm_model as fit_gamm_model,
)
from ecoscope_workflows_ext_gamm_trend_analysis.tasks import (
    predict_gamm_trends as predict_gamm_trends,
)

from ..params import Params


def main(params: Params):
    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    dependencies = {
        "workflow_details": [],
        "gee_project_name": [],
        "time_range": [],
        "groupers": [],
        "roi": [],
        "split_roi_groups": ["roi", "groupers"],
        "forest_cover_trends": ["gee_project_name", "split_roi_groups"],
        "gamm_model": ["forest_cover_trends"],
        "trend_predictions": ["gamm_model"],
        "forest_cover_chart": ["trend_predictions", "trend_predictions"],
        "persist_forest_cover": ["forest_cover_chart", "forest_cover_chart"],
        "forest_cover_widget": ["persist_forest_cover"],
        "grouped_forest_cover": ["forest_cover_widget"],
        "gamm_dashboard": [
            "workflow_details",
            "time_range",
            "grouped_forest_cover",
            "groupers",
        ],
    }

    nodes = {
        "workflow_details": Node(
            async_task=set_workflow_details.validate()
            .set_task_instance_id("workflow_details")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("workflow_details") or {}),
            method="call",
        ),
        "gee_project_name": Node(
            async_task=set_gee_connection.validate()
            .set_task_instance_id("gee_project_name")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("gee_project_name") or {}),
            method="call",
        ),
        "time_range": Node(
            async_task=set_time_range.validate()
            .set_task_instance_id("time_range")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "time_format": "%d %b %Y %H:%M:%S %Z",
                "timezone": {
                    "label": "UTC",
                    "tzCode": "UTC",
                    "name": "Universal Coordinated Time",
                    "utc": "+00:00",
                },
                "since": "2000-01-01T00:00:00.000Z",
                "until": "2023-12-31T23:59:59.000Z",
            }
            | (params_dict.get("time_range") or {}),
            method="call",
        ),
        "groupers": Node(
            async_task=set_groupers.validate()
            .set_task_instance_id("groupers")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("groupers") or {}),
            method="call",
        ),
        "roi": Node(
            async_task=load_spatial_features_group.validate()
            .set_task_instance_id("roi")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("roi") or {}),
            method="call",
        ),
        "split_roi_groups": Node(
            async_task=split_groups.validate()
            .set_task_instance_id("split_roi_groups")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("roi"),
                "groupers": DependsOn("groupers"),
            }
            | (params_dict.get("split_roi_groups") or {}),
            method="call",
        ),
        "forest_cover_trends": Node(
            async_task=extract_forest_cover_trends.validate()
            .set_task_instance_id("forest_cover_trends")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "client": DependsOn("gee_project_name"),
            }
            | (params_dict.get("forest_cover_trends") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["aoi"],
                "argvalues": DependsOn("split_roi_groups"),
            },
        ),
        "gamm_model": Node(
            async_task=fit_gamm_model.validate()
            .set_task_instance_id("gamm_model")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "time_column": "year",
                "value_column": "survival_area",
                "alpha": None,
                "lower_bound": None,
                "upper_bound": None,
                "optimize_alpha": True,
            }
            | (params_dict.get("gamm_model") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["dataframe"],
                "argvalues": DependsOn("forest_cover_trends"),
            },
        ),
        "trend_predictions": Node(
            async_task=predict_gamm_trends.validate()
            .set_task_instance_id("trend_predictions")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "time_values": None,
                "include_ci": True,
            }
            | (params_dict.get("trend_predictions") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["model_params"],
                "argvalues": DependsOn("gamm_model"),
            },
        ),
        "forest_cover_chart": Node(
            async_task=draw_historic_timeseries.validate()
            .set_task_instance_id("forest_cover_chart")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "dataframe": DependsOn("trend_predictions"),
                "current_value_column": "y",
                "time_column": "time",
                "current_value_title": "Observed Survival Area",
                "historic_min_column": "ci_lower",
                "historic_max_column": "ci_upper",
                "historic_mean_column": "predicted",
                "historic_mean_title": "GAM Mean",
                "historic_band_title": "GAM 95% CI",
                "layout_style": {
                    "title": "Forest survival area trend (GAM)",
                    "xaxis": {
                        "title": "Year",
                    },
                    "yaxis": {
                        "title": "Survival Area (acres)",
                    },
                },
                "upper_lower_band_style": {
                    "mode": "lines",
                    "line": {
                        "color": "green",
                    },
                },
                "historic_mean_style": None,
                "current_value_style": None,
            }
            | (params_dict.get("forest_cover_chart") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["dataframe"],
                "argvalues": DependsOn("trend_predictions"),
            },
        ),
        "persist_forest_cover": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_forest_cover")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "text": DependsOn("forest_cover_chart"),
            }
            | (params_dict.get("persist_forest_cover") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["text"],
                "argvalues": DependsOn("forest_cover_chart"),
            },
        ),
        "forest_cover_widget": Node(
            async_task=create_plot_widget_single_view.validate()
            .set_task_instance_id("forest_cover_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Forest Cover Trend Chart",
            }
            | (params_dict.get("forest_cover_widget") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("persist_forest_cover"),
            },
        ),
        "grouped_forest_cover": Node(
            async_task=merge_widget_views.validate()
            .set_task_instance_id("grouped_forest_cover")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("forest_cover_widget"),
            }
            | (params_dict.get("grouped_forest_cover") or {}),
            method="call",
        ),
        "gamm_dashboard": Node(
            async_task=gather_dashboard.validate()
            .set_task_instance_id("gamm_dashboard")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "details": DependsOn("workflow_details"),
                "time_range": DependsOn("time_range"),
                "widgets": [
                    DependsOn("grouped_forest_cover"),
                ],
                "groupers": DependsOn("groupers"),
            }
            | (params_dict.get("gamm_dashboard") or {}),
            method="call",
        ),
    }
    graph = Graph(dependencies=dependencies, nodes=nodes)
    results = graph.execute()
    return results
