# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, confloat, constr


class WorkflowDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., title="Workflow Name")
    description: Optional[str] = Field("", title="Workflow Description")


class HansenImage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    var: str = Field(
        ...,
        description="Hansen Global Forest Change dataset image name.",
        title="Image",
    )


class TreeCoverThreshold(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    threshold: Optional[confloat(ge=0.0, le=100.0)] = Field(
        60.0,
        description="Minimum tree cover percentage (0–100) to classify a pixel as forest.",
        title="Threshold",
    )


class ForestCoverTrends(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scale: Optional[int] = Field(
        30, description="Pixel scale in meters for reduction", title="Scale"
    )
    max_pixels: Optional[float] = Field(
        1000000000.0, description="Maximum pixels for reduction", title="Max Pixels"
    )


class ForestAnalysis(BaseModel):
    tree_cover_threshold: Optional[TreeCoverThreshold] = Field(None, title="")
    forest_cover_trends: Optional[ForestCoverTrends] = Field(None, title="")


class Url(str, Enum):
    https___tile_openstreetmap_org__z___x___y__png = (
        "https://tile.openstreetmap.org/{z}/{x}/{y}.png"
    )


class BaseMaps(BaseModel):
    url: Literal["https://tile.openstreetmap.org/{z}/{x}/{y}.png"] = Field(
        "https://tile.openstreetmap.org/{z}/{x}/{y}.png", title="Preset Layer URL"
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url1(str, Enum):
    https___server_arcgisonline_com_ArcGIS_rest_services_World_Street_Map_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}"


class BaseMaps1(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url2(str, Enum):
    https___server_arcgisonline_com_ArcGIS_rest_services_World_Imagery_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"


class BaseMaps2(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url3(str, Enum):
    https___server_arcgisonline_com_ArcGIS_rest_services_World_Topo_Map_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}"


class BaseMaps3(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url4(str, Enum):
    https___tiles_arcgis_com_tiles_POUcpLYXNckpLjnY_arcgis_rest_services_landDx_basemap_tiles_mapservice_MapServer_tile__z___y___x_ = "https://tiles.arcgis.com/tiles/POUcpLYXNckpLjnY/arcgis/rest/services/landDx_basemap_tiles_mapservice/MapServer/tile/{z}/{y}/{x}"


class BaseMaps4(BaseModel):
    url: Literal[
        "https://tiles.arcgis.com/tiles/POUcpLYXNckpLjnY/arcgis/rest/services/landDx_basemap_tiles_mapservice/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://tiles.arcgis.com/tiles/POUcpLYXNckpLjnY/arcgis/rest/services/landDx_basemap_tiles_mapservice/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class Url5(str, Enum):
    https___server_arcgisonline_com_arcgis_rest_services_Elevation_World_Hillshade_MapServer_tile__z___y___x_ = "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}"


class BaseMaps5(BaseModel):
    url: Literal[
        "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}"
    ] = Field(
        "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}",
        title="Preset Layer URL",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Layer Opacity",
    )


class BaseMaps6(BaseModel):
    url: Optional[
        constr(
            pattern=r"https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}([-a-zA-Z0-9()@:%_\+.~#?&//=\{\}]*)"
        )
    ] = Field(
        "https://example.tiles.com/{z}/{x}/{y}.png",
        description="The URL of a publicly accessible tiled raster service.",
        title="Custom Layer URL",
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        1,
        description="Set layer transparency from 1 (fully visible) to 0 (hidden).",
        title="Custom Layer Opacity",
    )
    max_zoom: Optional[int] = Field(
        20,
        description="Set the maximum zoom level to fetch tiles for.",
        title="Custom Layer Max Zoom",
    )
    min_zoom: Optional[int] = Field(
        0,
        description="Set the minimum zoom level to fetch tiles for.",
        title="Custom Layer Min Zoom",
    )


class BaseMapDefs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    base_maps: Optional[
        List[
            Union[
                BaseMaps,
                BaseMaps1,
                BaseMaps2,
                BaseMaps3,
                BaseMaps4,
                BaseMaps5,
                BaseMaps6,
            ]
        ]
    ] = Field(
        [
            {
                "url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}",
                "opacity": 1,
                "max_zoom": 20,
            },
            {
                "url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
                "opacity": 0.5,
                "max_zoom": 20,
            },
        ],
        description="Select tile layers to use as base layers in map outputs. The first layer in the list will be the bottommost layer displayed.",
        title=" ",
    )


class Metric(str, Enum):
    AIC = "AIC"
    BIC = "BIC"
    Euclidean = "Euclidean"
    MSE = "MSE"
    R_Squared = "R-Squared"


class Family(str, Enum):
    Gaussian = "Gaussian"
    Poisson = "Poisson"
    Binomial = "Binomial"


class GammModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    metric: Optional[Metric] = Field(
        "AIC", description="Metric for optimization", title="Metric"
    )
    degree_of_freedom: Optional[int] = Field(
        10, description="Degrees of freedom for spline basis", title="Degree Of Freedom"
    )
    degree: Optional[int] = Field(
        3, description="Degree of B-spline basis", title="Degree"
    )
    family: Optional[Family] = Field(
        "Gaussian", description="Distribution family for GLM", title="Family"
    )


class TrendAnalysis(BaseModel):
    gamm_model: Optional[GammModel] = Field(None, title="")


class MapWidgetTitle(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str = Field(
        ..., description="Title displayed on the forest change map.", title="Map Title"
    )


class ChartWidgetTitle(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str = Field(
        ...,
        description="Title displayed on the forest cover trend chart.",
        title="Trend Chart Title",
    )


class Dashboard(BaseModel):
    map_widget_title: Optional[MapWidgetTitle] = Field(None, title="")
    chart_widget_title: Optional[ChartWidgetTitle] = Field(None, title="")


class GoogleEarthEngineConnection(BaseModel):
    name: str = Field(..., title="Data Source")


class TimezoneInfo(BaseModel):
    label: str = Field(..., title="Label")
    tzCode: str = Field(..., title="Tzcode")
    name: str = Field(..., title="Name")
    utc: str = Field(..., title="Utc")


class SpatialGrouper(BaseModel):
    spatial_index_name: str = Field(..., title="Spatial Regions")


class TemporalGrouper(BaseModel):
    temporal_index: str = Field(..., title="Time")


class ValueGrouper(BaseModel):
    index_name: str = Field(..., title="Category")


class EarthRangerSpatialFeatures(BaseModel):
    data_source: str = Field(
        ...,
        description="Select one of your configured EarthRanger data sources.",
        title="Data Source",
    )
    spatial_features_group_name: str = Field(
        ...,
        description="Name of the spatial features group in EarthRanger",
        title="Spatial Features Group Name",
    )


class LocalFileSpatialFeatures(BaseModel):
    file_path: str = Field(
        ...,
        description="Path to geoparquet (.parquet) or geopackage (.gpkg) file",
        title="File Path",
    )
    name_column: str = Field(
        ..., description="Column to use as region name", title="Name Column"
    )
    layer: Optional[str] = Field(
        None,
        description="Layer name (only applicable to geopackage files)",
        title="Layer",
    )


class RemoteFileSpatialFeatures(BaseModel):
    url: str = Field(
        ...,
        description="URL to geoparquet (.parquet) or geopackage (.gpkg) file",
        title="Url",
    )
    name_column: str = Field(
        ..., description="Column to use as region name", title="Name Column"
    )
    layer: Optional[str] = Field(
        None,
        description="Layer name (only applicable for geopackage files)",
        title="Layer",
    )


class GeeProjectName(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data_source: GoogleEarthEngineConnection = Field(
        ..., description="Select one of your configured data sources.", title=""
    )


class TimeRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    since: datetime = Field(
        ...,
        description="Start year of the analysis. The Hansen dataset baseline always starts from 2000.",
        title="Since",
    )
    until: datetime = Field(
        ...,
        description="End year of the analysis. Depends on the Hansen dataset selected (e.g. UMD/hansen/global_forest_change_2024_v1_12 covers up to 2024).",
        title="Until",
    )
    timezone: Optional[TimezoneInfo] = Field(None, title="Timezone")


class Groupers(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    groupers: Optional[List[ValueGrouper]] = Field(
        [{"index_name": "name"}],
        description="            Specify how the data should be grouped to create the views for your dashboard.\n            This field is optional; if left blank, all the data will appear in a single view.\n            ",
        title=" ",
    )


class Roi(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    config: Union[LocalFileSpatialFeatures, RemoteFileSpatialFeatures] = Field(
        ..., title="Spatial Feature Data Source"
    )


class FormData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workflow_details: Optional[WorkflowDetails] = Field(
        None,
        description="Add information that will help to differentiate this workflow from another.",
        title="Set Workflow Details",
    )
    gee_project_name: Optional[GeeProjectName] = Field(
        None, title="Connect to Earth Engine"
    )
    time_range: Optional[TimeRange] = Field(
        None, description="Choose the period of time to analyze.", title="Time Range"
    )
    hansen_image: Optional[HansenImage] = Field(None, title="Hansen Dataset")
    groupers: Optional[Groupers] = Field(None, title="Set Groupers")
    roi: Optional[Roi] = Field(None, title="Load Region of Interest")
    Forest_Analysis: Optional[ForestAnalysis] = Field(
        None, alias="Forest Analysis", description=""
    )
    base_map_defs: Optional[BaseMapDefs] = Field(None, title="Base Maps")
    Trend_Analysis: Optional[TrendAnalysis] = Field(
        None,
        alias="Trend Analysis",
        description="Configure the GAM trend fitting parameters.",
    )
    Dashboard_1: Optional[Dashboard] = Field(
        None, alias="Dashboard", description="Configure the dashboard output titles."
    )
