# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


from __future__ import annotations

from enum import Enum
from typing import List, Optional, Union

from pydantic import BaseModel, ConfigDict, Field


class WorkflowDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., title="Workflow Name")
    description: Optional[str] = Field("", title="Workflow Description")


class ForestCoverTrends(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    tree_cover_threshold: Optional[float] = Field(
        60.0,
        description="Minimum tree cover percentage (0-100)",
        title="Tree Cover Threshold",
    )
    scale: Optional[int] = Field(
        30, description="Pixel scale in meters for reduction", title="Scale"
    )
    max_pixels: Optional[float] = Field(
        1000000000.0, description="Maximum pixels for reduction", title="Max Pixels"
    )


class Metric(str, Enum):
    AIC = "AIC"
    BIC = "BIC"
    Euclidean = "Euclidean"
    MSE = "MSE"
    R_Squared = "R-Squared"


class Family(str, Enum):
    Gaussian = "Gaussian"
    Poisson = "Poisson"
    Binomial = "Binomial"


class GammModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    metric: Optional[Metric] = Field(
        "AIC", description="Metric for optimization", title="Metric"
    )
    degree_of_freedom: Optional[int] = Field(
        20, description="Degrees of freedom for spline basis", title="Degree Of Freedom"
    )
    degree: Optional[int] = Field(
        3, description="Degree of B-spline basis", title="Degree"
    )
    family: Optional[Family] = Field(
        "Gaussian", description="Distribution family for GLM", title="Family"
    )


class GoogleEarthEngineConnection(BaseModel):
    name: str = Field(..., title="Data Source")


class SpatialGrouper(BaseModel):
    spatial_index_name: str = Field(..., title="Spatial Regions")


class TemporalGrouper(BaseModel):
    temporal_index: str = Field(..., title="Time")


class ValueGrouper(BaseModel):
    index_name: str = Field(..., title="Category")


class EarthRangerSpatialFeatures(BaseModel):
    data_source: str = Field(
        ...,
        description="Select one of your configured EarthRanger data sources.",
        title="Data Source",
    )
    spatial_features_group_name: str = Field(
        ...,
        description="Name of the spatial features group in EarthRanger",
        title="Spatial Features Group Name",
    )


class LocalFileSpatialFeatures(BaseModel):
    file_path: str = Field(
        ...,
        description="Path to geoparquet (.parquet) or geopackage (.gpkg) file",
        title="File Path",
    )
    name_column: str = Field(
        ..., description="Column to use as region name", title="Name Column"
    )
    layer: Optional[str] = Field(
        None,
        description="Layer name (only applicable to geopackage files)",
        title="Layer",
    )


class RemoteFileSpatialFeatures(BaseModel):
    url: str = Field(
        ...,
        description="URL to geoparquet (.parquet) or geopackage (.gpkg) file",
        title="Url",
    )
    name_column: str = Field(
        ..., description="Column to use as region name", title="Name Column"
    )
    layer: Optional[str] = Field(
        None,
        description="Layer name (only applicable for geopackage files)",
        title="Layer",
    )


class GeeProjectName(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data_source: GoogleEarthEngineConnection = Field(
        ..., description="Select one of your configured data sources.", title=""
    )


class Groupers(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    groupers: Optional[List[Union[ValueGrouper, TemporalGrouper, SpatialGrouper]]] = (
        Field(
            None,
            description="            Specify how the data should be grouped to create the views for your dashboard.\n            This field is optional; if left blank, all the data will appear in a single view.\n            ",
            title=" ",
        )
    )


class Roi(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    config: Union[
        LocalFileSpatialFeatures, RemoteFileSpatialFeatures, EarthRangerSpatialFeatures
    ] = Field(..., title="Spatial Feature Data Source")


class Params(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workflow_details: Optional[WorkflowDetails] = Field(
        None,
        description="Add information that will help to differentiate this workflow from another.",
        title="Set Workflow Details",
    )
    gee_project_name: Optional[GeeProjectName] = Field(
        None, title="Connect to Earth Engine"
    )
    groupers: Optional[Groupers] = Field(None, title="Set Groupers")
    roi: Optional[Roi] = Field(None, title="Load Region of Interest")
    forest_cover_trends: Optional[ForestCoverTrends] = Field(
        None, title="Extract Forest Cover Trends"
    )
    gamm_model: Optional[GammModel] = Field(None, title="Fit GAMM Model")
